spring.application.name=spring-rag-ollama-pgvector

#Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.init.pull-model-strategy=when-missing
spring.ai.ollama.init.timeout=5m
spring.ai.ollama.chat.options.model=mistral
spring.ai.vectorstore.pgvector.initialize-schema=true

spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=test
spring.datasource.password=test